spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  # freemaker
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  # 默认前缀
  mvc:
    view:
      prefix: /


# mybatis
mybatis:
  type-aliases-package: com.test.easypoi.mapper
  mapper-locations: classpath:mapper/*.xml

# 日志
logging:
  level:
    root: debug
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG